version: '3.5'

services:
  training:
    build: ./ml-kurkkumopo-training
    image: ml-kurkkumopo-training:latest
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    container_name: kurkkumopo-training
  backend:
    build: ./ml-kurkkumopo-backend
    image: ml-kurkkumopo-backend:latest 
    ports: 
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: kurkkumopo-backend
  frontend:
    build: ./ml-kurkkumopo-frontend
    image: ml-kurkkumopo-frontend:latest
    ports:
      - 3000:3000
    container_name: kurkkumopo-frontend
volumes:
  imgs:
  model:
