FROM alpine:3.10

ENV API_URL=http://localhost:8000

COPY . /mydir

RUN apk add --update nodejs npm && \
    addgroup -S node && adduser -S node -G node

USER node

RUN mkdir /home/node/code
WORKDIR home/node/code

COPY --chown=node:node package-lock.json package.json ./

RUN npm ci

COPY --chown=node:node . .

ENTRYPOINT npm start

