version: '3.5'

services:
  backend:
      image: backend:latest 
      ports: 
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
  frontend:
      image: frontend:latest
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
